# Gunakan base image Golang
FROM golang:1.23.4

# Set working directory di dalam container
WORKDIR /app

# Copy semua file ke dalam container
COPY . .

# Download dependencies
RUN go mod tidy

# Build aplikasi
RUN go build -o main .

# Expose port 8081
EXPOSE 8081

# Jalankan aplikasi
CMD ["./main"]